service: Booking-API
frameworkVersion: "3"
useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:AWS_PROFILE}
  region: eu-north-1
  iam:
    role: ${env:AWS_IAM_ROLE}

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  function1:
    handler: index.handler
  postBooking:
    handler: functions/postBooking/index.handler
    events:
      - httpApi:
          path: '/booking'
          method: 'POST'
  deleteBooking:        
    handler: functions/deleteBooking/index.handler
    events:
      - httpApi:
          path: '/booking'
          method: 'DELETE'
  getBookings:
    handler: function/getBookings/index.handler
    events:
      - httpApi:
          path: '/booking'
          method: 'GET' 


resources:
  Resources:
    bookingDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: room-booking-db
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id  
            KeyType: HASH  
        BillingMode: PAY_PER_REQUEST 