service: Booking-API
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  function1:
    handler: index.handler
